name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            # Start SSH agent
            eval "$(ssh-agent -s)"
          
            # Add existing key to SSH agent with passphrase provided by environment variable or secret
            echo "${{ secrets.GITHUB_SSH_KEYPHRASE }}" | ssh-add ~/.ssh/id_rsa

            # Pull latest code
            echo "Pulling latest code"
            cd /path-to-project/
            git pull origin main || { echo 'Git pull failed' ; exit 1; }
            yarn install
            pm2 restart processname --update-env
